
import { GoogleGenAI, Modality } from "@google/genai";

// Ensure the API key is available from environment variables
const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  throw new Error("API_KEY environment variable not set. Please set it in your environment.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export type DetailLevel = 'low' | 'medium' | 'high';

const prompts: Record<DetailLevel, string> = {
  low: 'Transform this photo into a simple, minimalist line drawing. Focus only on the main outlines and contours with almost no shading. The background must be a clean white.',
  medium: 'Transform this photo into an elegant, hand-drawn pencil sketch. Focus on clean lines, subtle shading, and artistic expression, while preserving the key features of the original image. The background should be a clean white.',
  high: 'Transform this photo into a highly detailed, photorealistic pencil sketch. Emphasize fine details, intricate textures, and realistic shading to create a rich, lifelike drawing. The background must be a clean white.',
};

/**
 * Generates a sketch from a given image using the Gemini API.
 * @param base64ImageData The base64-encoded image data (without the data URL prefix).
 * @param mimeType The MIME type of the image (e.g., 'image/jpeg').
 * @param detailLevel The desired level of detail for the sketch.
 * @returns A promise that resolves to the base64 data URL of the generated sketch.
 */
export const generateSketch = async (base64ImageData: string, mimeType: string, detailLevel: DetailLevel): Promise<string> => {
  try {
    const promptText = prompts[detailLevel];
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: promptText,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    // Validate API response structure
    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No candidates returned by the API.");
    }

    const candidate = response.candidates[0];
    if (!candidate.content || !candidate.content.parts) {
      throw new Error("Invalid response structure from the API.");
    }

    for (const part of candidate.content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const responseMimeType = part.inlineData.mimeType;
        // The API returns PNGs for this kind of generation
        return `data:${responseMimeType};base64,${base64ImageBytes}`;
      }
    }
    
    // If no image part is found in the response
    throw new Error("No image was generated by the API.");

  } catch (error: unknown) {
    console.error("Error calling Gemini API:", error);
    // Re-throw a more user-friendly error
    if (error instanceof Error) {
      throw new Error(`Failed to generate sketch: ${error.message}`);
    }
    throw new Error("The AI model could not process the image. Please try a different one.");
  }
};
